name: Manual Build

on:
  workflow_dispatch:
    inputs:
      build_platform:
        description: '选择构建平台'
        required: true
        default: 'all'
        type: choice
        options:
        - all
        - windows
        - macos
        - linux

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: windows
            artifact-name: ClearMeta-Windows
          - os: macos-latest
            platform: macos
            artifact-name: ClearMeta-macOS
          - os: ubuntu-latest
            platform: linux
            artifact-name: ClearMeta-Linux
        exclude:
          - os: ${{ github.event.inputs.build_platform == 'windows' && 'macos-latest' || 'skip' }}
          - os: ${{ github.event.inputs.build_platform == 'windows' && 'ubuntu-latest' || 'skip' }}
          - os: ${{ github.event.inputs.build_platform == 'macos' && 'windows-latest' || 'skip' }}
          - os: ${{ github.event.inputs.build_platform == 'macos' && 'ubuntu-latest' || 'skip' }}
          - os: ${{ github.event.inputs.build_platform == 'linux' && 'windows-latest' || 'skip' }}
          - os: ${{ github.event.inputs.build_platform == 'linux' && 'macos-latest' || 'skip' }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create placeholder QR code
      run: |
        python -c "
        from PIL import Image, ImageDraw
        from pathlib import Path
        if not Path('sponsor_qr.png').exists():
            img = Image.new('RGB', (200, 200), color='white')
            draw = ImageDraw.Draw(img)
            draw.rectangle([10, 10, 190, 190], outline='black', width=2)
            draw.text((100, 80), '赞助', fill='black', anchor='mm')
            draw.text((100, 100), '二维码', fill='black', anchor='mm')
            draw.text((100, 120), '占位图', fill='gray', anchor='mm')
            img.save('sponsor_qr.png')
        "

    - name: Install Linux dependencies
      if: matrix.platform == 'linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libxcb-xinerama0

    - name: Build with PyInstaller
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          pyinstaller --noconfirm --windowed --onefile --name ClearMeta --add-data "sponsor_qr.png;." --add-data "README.md;." main.py
        elif [ "$RUNNER_OS" == "macOS" ]; then
          pyinstaller ClearMeta.spec
        else
          pyinstaller --noconfirm --windowed --name ClearMeta --add-data "sponsor_qr.png:." --add-data "README.md:." main.py
        fi
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.artifact-name }}
        path: |
          dist/
